spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/eOrderServiceDB
    username: root
    password: toor
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: public
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    ROOT: INFO
    com.midnightsun: DEBUG

server:
  port: 8081

global:
  exception-handling:
    debug-message: TRUE

rabbitmq:
  queues:
    ns_queue: notification-queue
    ps_queue: product-queue
  exchanges:
    ns_exchange: notification-exchange
    ps_exchange: product-exchange
  routings:
    ns_key: notification-routing-key
    ps_key: product-routing-key

info:
  application:
    name: Order Service
    version: 0.0.1
    description: Service managing orders in eCart Application
