spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/eOrderServiceDB
    username: root
    password: toor
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: public
  logging:
    level:
      org:
        springframework: INFO
    output:
      ansi:
        enabled: ALWAYS


server:
  port: 8081

info:
  application:
    name: Order Service
    version: 0.0.1
    description: Service managing orders in eCart Application
