version: '3.8'

#username: guest
#password: guest

services:
  e-rabbitmq:
    image: rabbitmq:3.12.0-management
    container_name: e-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - e-rabbitmq:/var/lib/rabbitmq/
      - e-rabbitmq:/var/log/rabbitmq

volumes:
  e-rabbitmq: