spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    smtp:
      auth: true
    properties:
      mail:
        smtp:
          starttls:
            enable: true

logging:
  level:
    ROOT: INFO
    com.midnightsun: DEBUG

server:
  port: 8083

rabbitmq:
  queues:
    ns_queue: notification-queue
  exchanges:
    ns_exchange: notification-exchange
  routings:
    ns_key: notification-routing-key

info:
  application:
    name: Notification Service
    version: 0.0.1
    description: Service responsible for notification in eCart Application
